version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile.prod
    image: summersummerwhy/octodocs-nginx

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile.prod
    image: summersummerwhy/octodocs-backend

  websocket:
    build:
      context: .
      dockerfile: ./services/websocket/Dockerfile.prod
    image: summersummerwhy/octodocs-websocket
