# 빌드 스테이지
FROM node:20-alpine as builder

WORKDIR /app/apps/websocket

# 소스 코드 복사
COPY . .

# 빌드
RUN yarn turbo build

# 프로덕션 스테이지
FROM octodocs-modules

WORKDIR /app

COPY --from=builder /app/apps/websocket/dist ./apps/websocket/dist

# 프로덕션 모드로 실행
ENV NODE_ENV=production

EXPOSE 4242

CMD ["yarn", "start:websocket"]