FROM octodocs-modules:latest

# 소스 코드 복사 
COPY . .
COPY ./.env.server /app/apps/websocket/.env

WORKDIR /app/apps/websocket

# 빌드
RUN yarn build

# 프로덕션 모드로 실행
ENV NODE_ENV=production

EXPOSE 4242

CMD ["yarn", "start:prod"]