FROM octodocs-modules:latest

EXPOSE 4242

COPY ./apps/websocket /app/apps/websocket
COPY ./tsconfig.json /app/tsconfig.json
COPY ./nest-cli.json /app/nest-cli.json
COPY ./libs /app/libs

CMD ["sh", "-c", "cd app/apps/websocket && yarn dev"]
