# 만약 octodocs-modules가 원격 저장소에 없으면 node 이미지를 사용한다.
FROM node:20-alpine

WORKDIR /app

# 호이스팅을 위해
COPY package.json yarn.lock ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/
COPY apps/websocket/package.json ./apps/websocket/

# 의존성 설치
RUN yarn install --check-files