FROM growth123/octodocs-modules:latest

# 소스 코드 복사
# 덮어씌워지지만 node_modules를 .dockerignore에 등록했기 때문에 node_modules는 원래 있던 그대로
COPY . /app

WORKDIR /app/apps/backend

# 빌드
RUN apt update && apt install wget -y && yarn build

# 프로덕션 모드로 실행
ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start"]