# 빌드 스테이지
FROM node:20-alpine as builder

WORKDIR /app/apps/backend

# 소스 코드 복사
COPY . .

# 백엔드 빌드
RUN yarn build

# 실행 스테이지
FROM octodocs-modules:latest

WORKDIR /app

# wget 설치
RUN apk add --no-cache wget

# 프로덕션에 필요한 파일만 복사
COPY --from=builder /app/apps/backend/dist ./apps/backend/dist

ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start:backend"]
