FROM growth123/octodocs-modules:latest

# 소스 코드 복사
COPY . .

WORKDIR /app/apps/backend


# 빌드
RUN apt update && apt install wget -y && yarn build

# 프로덕션 모드로 실행
ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start:prod"]