FROM octodocs-modules:latest

COPY ./apps/scheduler /app/apps/scheduler
COPY ./tsconfig.json /app/tsconfig.json
COPY ./nest-cli.json /app/nest-cli.json
COPY ./libs /app/libs

CMD ["sh", "-c", "cd app/apps/scheduler && yarn dev"]
